---
apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s
spec:
  containers:
    - name: hello-k8s
      image: atrakic/hello-k8s:0.0.1
---
kind: Service
apiVersion: v1
metadata:
  name: hello-k8s-svc
spec:
  selector:
    app: hello-k8s
  ports:
  # Default port used by the image
  - port: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-k8s-ingress
spec:
  rules:
  - http:
      paths:
      - path: /hello
        backend:
          serviceName: hello-k8s-svc
          servicePort: 3000
